#
# Make file for the the biggest common denominator
#

CFLAGS = -std=c99 -pedantic -Wall -Wextra

all:
	gcc $(CFLAGS) -o BiggestCommonDenominator.exe bcd1.c
	./BiggestCommonDenominator.exe
	gcc $(CFLAGS) -o BiggestCommonDenominatorImproved.exe bcd2.c
	./BiggestCommonDenominatorImproved.exe
	gcc $(CFLAGS) -o BiggestCommonDenominatorAlternative.exe bcd3.c
	./BiggestCommonDenominatorAlternative.exe

