CC = clang
CFLAGS = -std=c99 -pedantic -Wall -Wextra -Wfloat-equal -Wshadow -Wunused-parameter

blatt03_1.exe:
	$(CC) $(CFLAGS) -o blatt03_1.exe blatt03_1.c
	./blatt03_1.exe

blatt03_2.exe:
	$(CC) $(CFLAGS) -o blatt03_2.exe blatt03_2.c
	./blatt03_2.exe

blatt03_3.exe:
	$(CC) $(CFLAGS) -o blatt03_3.exe blatt03_3.c
	./blatt03_3.exe

clean:
	@rm *.exe
