CC = clang
CFLAGS = -std=c99 -pedantic -Wall -Wextra -Wfloat-equal -Wshadow -Wunused-parameter

default:
	$(CC) $(CFLAGS) -o blatt07_1.exe blatt07_1.c
	./blatt07_1.exe

mandel:
	$(CC) $(CFLAGS) -o blatt07_2.exe blatt07_2.c
	./blatt07_2.exe

clean:
	@rm *.exe
