CC = clang
CFLAGS = -std=c99 -pedantic -Wall -Wextra -Wfloat-equal -Wshadow -Wunused-parameter

blatt02_1.exe:
	$(CC) $(CFLAGS) -o blatt02_1.exe blatt02_1.c
	./blatt02_1.exe

blatt02_2.exe:
	$(CC) $(CFLAGS) -o blatt02_2.exe blatt02_2.c
	./blatt02_2.exe 30

blatt02_3.exe:
	$(CC) $(CFLAGS) -o blatt02_3.exe blatt02_3.c
	./blatt02_3.exe

clean:
	@rm *.exe

